### ISSUE TITLE
ggg-easy-07

### ISSUE THREAD

**Issue by ladislav** [ligi/gobandroid#202] opened 2017-06-02 09:37 UTC
Hi. In older versions of the software, the solution to this specific problem was correct. I checked gogameguru Git, and the PDF is correct there.

**Comment by ligi** [comment] 2017-06-02 15:20
can you give some more details please ?

**Comment by ladislav** [comment] 2017-06-02 16:05
The correct placement of the black's move #5 is at the 1,2 point not at at the 1,1 point in the corner, as the program incorrectly claims.

Other problematic changes occurred in:
ggg-easy-16
ggg-easy-42
ggg-easy-43
ggg-easy-45
ggg-easy-50
ggg-easy-65
ggg-easy-67
ggg-easy-68
ggg-easy-77
ggg-easy-79
ggg-easy-92
ggg-easy-93
ggg-easy-94
ggg-easy-96
ggg-easy-109
ggg-easy-114
ggg-easy-137
Did you take the SGF files from the gogameguru place?

**Comment by ligi** [comment] 2017-06-03 11:52
Yes - they are directly 1:1 from gogameguru @gthazmatt can you check if this is caused by the new loading speed-up PRs?

**Comment by gthazmatt** [comment] 2017-06-22 15:31
I have been swamped between work and trying to close on a house. Hopefully I can dedicate some time to this over the weekend.

**Comment by ligi** [comment] 2017-06-22 15:48
Hope everything went fine with the House! Great if you could look over it at the weekend - otherwise I will have to do it - getting more and more comments about this.

**Comment by gthazmatt** [comment] 2017-06-26 22:02
This did come from my changes, but not from the most recent changes. It was introduced in version 2.5.5 with commit 213fd72. I used the following simple test to find when the error occurred (ggg-easy-07.sgf needs to be copied to the test_sgfs directory). I commented above the line where the next move is missing. The specific code change that causes it to be missing is the call to board.setCell(cell, getCellStatus()) in GoMove.apply, though I'm not sure why it has that effect. I'll try to look into it more when I have more time.

```
    @Test
    fun testCorrectMove() {
        val game = SGFReader.sgf2game(readAsset("test_sgfs/ggg-easy-07.sgf"), null)
        var move: GoMove? = game?.actMove
        assertThat(move!!.nextMoveVariationCount).isEqualTo(4)
        move = move.getNextMoveOnCell(CellImpl(16,16))
        move = move!!.getNextMoveOnCell(CellImpl(18,16))
        move = move!!.getNextMoveOnCell(CellImpl(18,17))
        move = move!!.getNextMoveOnCell(CellImpl(17,18))

        //the next move is missing from the variation list
        move = move!!.getNextMoveOnCell(CellImpl(18,17))
        move = move!!.getNextMoveOnCell(CellImpl(18,18))
        move = move!!.getNextMoveOnCell(CellImpl(18,17))
        assertThat(move!!.comment).isEqualToIgnoringCase("CORRECT")
    }
```

**Comment by ligi** [comment] 2018-05-31 21:30
should be fixed

**Closed by ligi** 2018-05-31 21:30 UTC
