### ISSUE TITLE
Gobandroid cannot find GnuGo

### ISSUE THREAD

**Issue by ldesousa** [ligi/gobandroid#168] opened 2016-04-05 19:54 UTC
Set up:
Android 6.0.1
Gobandroid 2.3.0
GnuGo 0.6

When I select the GnuGo option for one of the players in a new game I get the following message: "GnuGo not installed - to proceed please install!"

**Comment by ligi** [comment] 2016-04-05 20:27
what happens when you click the link to install?

**Comment by ldesousa** [comment] 2016-04-05 20:38
It replies: "No such app found."

I just upgraded Gobandroid to version 2.6.3 and this issue remains.

**Comment by ligi** [comment] 2016-04-05 21:22
the play store says no app found? Can you make a screenshot?

**Comment by ldesousa** [comment] 2016-04-06 08:00
The screenshots are attached. Apparently, the Play Store never comes into play.

![screenshot_20160406-095309](https://cloud.githubusercontent.com/assets/1137878/14309663/3d8d0712-fbde-11e5-83b1-ed95f9b66b18.png)

![screenshot_20160406-095316](https://cloud.githubusercontent.com/assets/1137878/14309664/403455ce-fbde-11e5-8484-8328818bf3d9.png)

**Comment by ligi** [comment] 2016-04-06 10:02
this is really strange - can you tell me more about your device and
android version
If you just want to play you can install from here:
 https://github.com/ligi/gobandroid-ai-gnugo/releases/tag/2.1.1

but I would love to know what goes on there - but I cannot reproduce it

**Comment by ldesousa** [comment] 2016-04-06 11:17
I removed version 0.6 (installed by the Play Store) and installed version 2.1.1 manually available from here. Now I can assign GnuGo to one or both the players.

There must be something wrong with the version at the Play Store. Another thing: it would be better to have GnuGo also available from F-Droid.

**Comment by ligi** [comment] 2016-04-06 13:59
when you uninstall gnugo 2.1.1 ( and you do not have this 0.6 installed ) - is the install flow working then?
GnuGo on F-Droid will not be done by me - if anyone else wants to put in the time for it fine - but I will not - everything is open so everyone has the chance to do it - but to be clear from the beginning: It will not be me ..

**Comment by ldesousa** [comment] 2016-04-06 14:19
Nope. If i uninstall version 2.2.1 then I get the flow you can see in the images above. It only works if I download the apk directly from GitHub.

P.S: If everything is open, why use the Play Store instead of F-Dorid?

**Comment by ligi** [comment] 2016-04-06 14:24
FDroid is a significant amount of work - with gnugo it gets really complicated as it is a NDK project ( native code ) - I don't even enjoy playing agains AI's - so I am not willing to put in this amount of work - but if you want to do - feel free!

Do you use any custom ROM? It is really strange that market:// url's cannot be resolved - also I cannot reproduce it - also tested on stock 6.0.1 as you stated you have - I have no plan on how to proceed here yet

**Comment by ldesousa** [comment] 2016-04-06 14:28
This is a stock Nexus 5X. I also have Gobandroid on a Samsung tablet and there I have no issues like this. I will try to reproduce this on another phone.

**Comment by ligi** [comment] 2016-04-06 14:31
Thanks for the info - really strange - I also tested on a nexus ( N7 ) - should literally be the same code in this corner

**Comment by ldesousa** [comment] 2016-04-06 15:19
I was able to reproduce this issue on a Galaxy SII (Android 4.0.3). However, it displays an additional dialogue after I select "Proceed to install":

![screenshot_2016-04-06-17-13-12](https://cloud.githubusercontent.com/assets/1137878/14321961/9458f942-fc1b-11e5-8f05-bb137968fb88.png)

If I select F-Droid I get the "No such App found." message. If I select the Play Store I am directed to the GnuGo install page.

For whatever reason, this intermediate dialogue is absent on the Nexus 5X.

**Comment by ligi** [comment] 2016-04-06 15:24
Ah this makes it clear: the "No such app found" comes from FDroid - when fdroid catches the market:// URL for gnugo. On the Nexus you perhaps selected "Use by default" for market and FDroid. 
So the fix for this is when opening the market:// url - only allow it for google-play

**Comment by ldesousa** [comment] 2016-04-06 15:29
But it does not explain why Gobandroid is unable to locate GnuGo when it is installed from the Play Store...

**Comment by ligi** [comment] 2016-04-06 15:31
it does - FDroid is opening all market:// urls on this device as it is default - it does not matter which market was used to install the app. You have to go to fdroid and clear the defaults

**Comment by ildar** [comment] 2016-04-07 10:02
Guys, regarding GnuGo → F-Droid.
FYI, you both don't need to push it to the F-Droid as it is usually done by
F-Droid staff. Someone who is interested just needs to file a request at
forum.

**Comment by ligi** [comment] 2016-04-07 12:06
It is already in the forum: https://f-droid.org/forums/topic/gobandroid-gobandroid-ai-gnugo/ ( since 2014 )

**Closed** 2016-04-09 17:47 UTC

**Comment by licaon-kter** [comment] 2023-02-06 13:20
fyi https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12567
